// ─── Team Home Venue Map ───────────────────────────────────────────────────────
// Maps sport + team name keywords → official home venue name.
// Used to auto-populate the venue field when a captain selects a team.
// ⚠️  Update when teams relocate or rename their arenas.
// ─────────────────────────────────────────────────────────────────────────────

const VENUES = {

  // ── NBA ─────────────────────────────────────────────────────────────────────
  NBA: {
    "hawks":          "State Farm Arena",
    "celtics":        "TD Garden",
    "nets":           "Barclays Center",
    "hornets":        "Spectrum Center",
    "bulls":          "United Center",
    "cavaliers":      "Rocket Mortgage FieldHouse",
    "cavs":           "Rocket Mortgage FieldHouse",
    "mavericks":      "American Airlines Center",
    "mavs":           "American Airlines Center",
    "nuggets":        "Ball Arena",
    "pistons":        "Little Caesars Arena",
    "warriors":       "Chase Center",
    "rockets":        "Toyota Center",
    "pacers":         "Gainbridge Fieldhouse",
    "clippers":       "Intuit Dome",
    "lakers":         "Crypto.com Arena",
    "grizzlies":      "FedExForum",
    "heat":           "Kaseya Center",
    "bucks":          "Fiserv Forum",
    "timberwolves":   "Target Center",
    "wolves":         "Target Center",
    "pelicans":       "Smoothie King Center",
    "knicks":         "Madison Square Garden",
    "thunder":        "Paycom Center",
    "magic":          "Kia Center",
    "76ers":          "Wells Fargo Center",
    "sixers":         "Wells Fargo Center",
    "suns":           "Footprint Center",
    "trail blazers":  "Moda Center",
    "blazers":        "Moda Center",
    "kings":          "Golden 1 Center",
    "spurs":          "Frost Bank Center",
    "raptors":        "Scotiabank Arena",
    "jazz":           "Delta Center",
    "wizards":        "Capital One Arena",
  },

  // ── NFL ─────────────────────────────────────────────────────────────────────
  NFL: {
    "cardinals":      "State Farm Stadium",
    "falcons":        "Mercedes-Benz Stadium",
    "ravens":         "M&T Bank Stadium",
    "bills":          "Highmark Stadium",
    "panthers":       "Bank of America Stadium",
    "bears":          "Soldier Field",
    "bengals":        "Paycor Stadium",
    "browns":         "Huntington Bank Field",
    "cowboys":        "AT&T Stadium",
    "broncos":        "Empower Field at Mile High",
    "lions":          "Ford Field",
    "packers":        "Lambeau Field",
    "texans":         "NRG Stadium",
    "colts":          "Lucas Oil Stadium",
    "jaguars":        "EverBank Stadium",
    "chiefs":         "GEHA Field at Arrowhead Stadium",
    "raiders":        "Allegiant Stadium",
    "chargers":       "SoFi Stadium",
    "rams":           "SoFi Stadium",
    "dolphins":       "Hard Rock Stadium",
    "vikings":        "U.S. Bank Stadium",
    "patriots":       "Gillette Stadium",
    "saints":         "Caesars Superdome",
    "giants":         "MetLife Stadium",
    "jets":           "MetLife Stadium",
    "eagles":         "Lincoln Financial Field",
    "steelers":       "Acrisure Stadium",
    "49ers":          "Levi's Stadium",
    "seahawks":       "Lumen Field",
    "buccaneers":     "Raymond James Stadium",
    "bucs":           "Raymond James Stadium",
    "titans":         "Nissan Stadium",
    "commanders":     "Northwest Stadium",
  },

  // ── MLB ─────────────────────────────────────────────────────────────────────
  MLB: {
    "diamondbacks":   "Chase Field",
    "d-backs":        "Chase Field",
    "braves":         "Truist Park",
    "orioles":        "Oriole Park at Camden Yards",
    "red sox":        "Fenway Park",
    "cubs":           "Wrigley Field",
    "white sox":      "Guaranteed Rate Field",
    "reds":           "Great American Ball Park",
    "guardians":      "Progressive Field",
    "rockies":        "Coors Field",
    "tigers":         "Comerica Park",
    "astros":         "Minute Maid Park",
    "royals":         "Kauffman Stadium",
    "angels":         "Angel Stadium",
    "dodgers":        "Dodger Stadium",
    "marlins":        "loanDepot park",
    "brewers":        "American Family Field",
    "twins":          "Target Field",
    "mets":           "Citi Field",
    "yankees":        "Yankee Stadium",
    "athletics":      "Sutter Health Park",
    "phillies":       "Citizens Bank Park",
    "pirates":        "PNC Park",
    "padres":         "Petco Park",
    "giants":         "Oracle Park",
    "mariners":       "T-Mobile Park",
    "cardinals":      "Busch Stadium",
    "rays":           "Tropicana Field",
    "rangers":        "Globe Life Field",
    "blue jays":      "Rogers Centre",
    "nationals":      "Nationals Park",
  },

  // ── NHL ─────────────────────────────────────────────────────────────────────
  NHL: {
    "ducks":          "Honda Center",
    "bruins":         "TD Garden",
    "sabres":         "KeyBank Center",
    "flames":         "Scotiabank Saddledome",
    "hurricanes":     "PNC Arena",
    "canes":          "PNC Arena",
    "blackhawks":     "United Center",
    "avalanche":      "Ball Arena",
    "avs":            "Ball Arena",
    "blue jackets":   "Nationwide Arena",
    "stars":          "American Airlines Center",
    "red wings":      "Little Caesars Arena",
    "oilers":         "Rogers Place",
    "panthers":       "Amerant Bank Arena",
    "kings":          "Crypto.com Arena",
    "wild":           "Xcel Energy Center",
    "canadiens":      "Bell Centre",
    "habs":           "Bell Centre",
    "predators":      "Bridgestone Arena",
    "preds":          "Bridgestone Arena",
    "devils":         "Prudential Center",
    "islanders":      "UBS Arena",
    "rangers":        "Madison Square Garden",
    "senators":       "Canadian Tire Centre",
    "sens":           "Canadian Tire Centre",
    "flyers":         "Wells Fargo Center",
    "penguins":       "PPG Paints Arena",
    "pens":           "PPG Paints Arena",
    "sharks":         "SAP Center",
    "kraken":         "Climate Pledge Arena",
    "blues":          "Enterprise Center",
    "lightning":      "Amalie Arena",
    "bolts":          "Amalie Arena",
    "maple leafs":    "Scotiabank Arena",
    "leafs":          "Scotiabank Arena",
    "utah hockey":    "Delta Center",
    "canucks":        "Rogers Arena",
    "golden knights": "T-Mobile Arena",
    "capitals":       "Capital One Arena",
    "caps":           "Capital One Arena",
    "jets":           "Canada Life Centre",
  },

  // ── MLS ─────────────────────────────────────────────────────────────────────
  MLS: {
    "galaxy":           "Dignity Health Sports Park",
    "lafc":             "BMO Stadium",
    "atlanta united":   "Mercedes-Benz Stadium",
    "sounders":         "Lumen Field",
    "portland timbers": "Providence Park",
    "timbers":          "Providence Park",
    "red bulls":        "Red Bull Arena",
    "nycfc":            "Yankee Stadium",
    "new york city":    "Yankee Stadium",
    "columbus crew":    "Lower.com Field",
    "crew":             "Lower.com Field",
    "sporting kc":      "Children's Mercy Park",
    "sporting kansas":  "Children's Mercy Park",
    "fc dallas":        "Toyota Stadium",
    "chicago fire":     "Soldier Field",
    "toronto fc":       "BMO Field",
    "minnesota united": "Allianz Field",
    "loons":            "Allianz Field",
    "inter miami":      "Chase Stadium",
    "nashville sc":     "GEODIS Park",
    "austin fc":        "Q2 Stadium",
    "st. louis city":   "CITYPARK",
    "real salt lake":   "America First Field",
    "rsl":              "America First Field",
  },

  // ── WNBA ────────────────────────────────────────────────────────────────────
  WNBA: {
    "sky":              "Wintrust Arena",
    "chicago sky":      "Wintrust Arena",
    "dream":            "Gateway Center Arena",
    "fever":            "Gainbridge Fieldhouse",
    "sparks":           "Crypto.com Arena",
    "lynx":             "Target Center",
    "liberty":          "Barclays Center",
    "sun":              "Mohegan Sun Arena",
    "mystics":          "Capital One Arena",
    "wings":            "College Park Center",
    "mercury":          "Footprint Center",
    "storm":            "Climate Pledge Arena",
    "aces":             "Michelob Ultra Arena",
    "las vegas aces":   "Michelob Ultra Arena",
  },

  // ── NCAA Football ────────────────────────────────────────────────────────────
  "ncaa-football": {
    "alabama":          "Bryant-Denny Stadium",
    "crimson tide":     "Bryant-Denny Stadium",
    "ohio state":       "Ohio Stadium",
    "buckeyes":         "Ohio Stadium",
    "michigan":         "Michigan Stadium",
    "wolverines":       "Michigan Stadium",
    "georgia":          "Sanford Stadium",
    "bulldogs":         "Sanford Stadium",
    "clemson":          "Memorial Stadium",
    "notre dame":       "Notre Dame Stadium",
    "fighting irish":   "Notre Dame Stadium",
    "texas":            "Darrell K Royal–Texas Memorial Stadium",
    "longhorns":        "Darrell K Royal–Texas Memorial Stadium",
    "oklahoma":         "Gaylord Family Oklahoma Memorial Stadium",
    "sooners":          "Gaylord Family Oklahoma Memorial Stadium",
    "lsu":              "Tiger Stadium",
    "usc":              "Los Angeles Memorial Coliseum",
    "trojans":          "Los Angeles Memorial Coliseum",
    "oregon":           "Autzen Stadium",
    "ducks":            "Autzen Stadium",
    "penn state":       "Beaver Stadium",
    "nittany lions":    "Beaver Stadium",
    "florida":          "Ben Hill Griffin Stadium",
    "gators":           "Ben Hill Griffin Stadium",
    "tennessee":        "Neyland Stadium",
    "volunteers":       "Neyland Stadium",
    "iowa":             "Kinnick Stadium",
    "hawkeyes":         "Kinnick Stadium",
    "auburn":           "Jordan-Hare Stadium",
    "wisconsin":        "Camp Randall Stadium",
    "badgers":          "Camp Randall Stadium",
    "utah":             "Rice-Eccles Stadium",
    "utes":             "Rice-Eccles Stadium",
    "michigan state":   "Spartan Stadium",
    "spartans":         "Spartan Stadium",
    "washington":       "Husky Stadium",
    "huskies":          "Husky Stadium",
    "florida state":    "Doak Campbell Stadium",
    "seminoles":        "Doak Campbell Stadium",
  },

  // ── NCAA Men's Basketball ─────────────────────────────────────────────────
  "ncaa-basketball": {
    "duke":             "Cameron Indoor Stadium",
    "blue devils":      "Cameron Indoor Stadium",
    "kentucky":         "Rupp Arena",
    "wildcats":         "Rupp Arena",
    "kansas":           "Allen Fieldhouse",
    "jayhawks":         "Allen Fieldhouse",
    "north carolina":   "Dean E. Smith Center",
    "tar heels":        "Dean E. Smith Center",
    "unc":              "Dean E. Smith Center",
    "uconn":            "Gampel Pavilion",
    "villanova":        "Finneran Pavilion",
    "gonzaga":          "McCarthey Athletic Center",
    "zags":             "McCarthey Athletic Center",
    "michigan state":   "Breslin Center",
    "ucla":             "Pauley Pavilion",
    "bruins":           "Pauley Pavilion",
    "arizona":          "McKale Center",
    "purdue":           "Mackey Arena",
    "boilermakers":     "Mackey Arena",
    "indiana":          "Simon Skjodt Assembly Hall",
    "hoosiers":         "Simon Skjodt Assembly Hall",
    "houston":          "Fertitta Center",
    "cougars":          "Fertitta Center",
    "marquette":        "Fiserv Forum",
    "louisville":       "KFC Yum! Center",
  },

  // ── NCAA Women's Basketball ───────────────────────────────────────────────
  "ncaa-wbasketball": {
    "uconn":            "Gampel Pavilion",
    "south carolina":   "Colonial Life Arena",
    "gamecocks":        "Colonial Life Arena",
    "iowa":             "Carver-Hawkeye Arena",
    "hawkeyes":         "Carver-Hawkeye Arena",
    "lsu":              "Pete Maravich Assembly Center",
    "stanford":         "Maples Pavilion",
    "tennessee":        "Thompson-Boling Arena",
    "notre dame":       "Purcell Pavilion",
    "baylor":           "Foster Pavilion",
    "bears":            "Foster Pavilion",
    "nc state":         "Reynolds Coliseum",
    "wolfpack":         "Reynolds Coliseum",
    "virginia tech":    "Cassell Coliseum",
    "hokies":           "Cassell Coliseum",
  },

  // ── NCAA Baseball ─────────────────────────────────────────────────────────
  "ncaa-baseball": {
    "lsu":              "Alex Box Stadium",
    "vanderbilt":       "Hawkins Field",
    "commodores":       "Hawkins Field",
    "florida":          "Condron Family Baseball Park",
    "gators":           "Condron Family Baseball Park",
    "texas":            "UFCU Disch-Falk Field",
    "arkansas":         "Baum-Walker Stadium",
    "razorbacks":       "Baum-Walker Stadium",
    "arizona":          "Hi Corbett Field",
    "stanford":         "Sunken Diamond",
    "miami":            "Mark Light Field",
    "oregon state":     "Goss Stadium",
    "beavers":          "Goss Stadium",
    "ole miss":         "Swayze Field",
    "rebels":           "Swayze Field",
    "texas a&m":        "Olsen Field",
    "aggies":           "Olsen Field",
    "tcu":              "Lupton Stadium",
    "horned frogs":     "Lupton Stadium",
  },

  // ── NCAA Hockey ──────────────────────────────────────────────────────────
  "ncaa-hockey": {
    "minnesota":        "3M Arena at Mariucci",
    "gophers":          "3M Arena at Mariucci",
    "north dakota":     "Ralph Engelstad Arena",
    "fighting hawks":   "Ralph Engelstad Arena",
    "boston university":"Agganis Arena",
    "terriers":         "Agganis Arena",
    "michigan":         "Yost Ice Arena",
    "wisconsin":        "LaBahn Arena",
    "denver":           "Magness Arena",
    "pioneers":         "Magness Arena",
    "boston college":   "Kelley Rink",
    "cornell":          "Lynah Rink",
    "quinnipiac":       "People's United Center",
    "bobcats":          "People's United Center",
  },
};

// ─── Lookup function ──────────────────────────────────────────────────────────
/**
 * Returns the home venue name for a team, or null if not found.
 * @param {string} teamName  e.g. "Miami Heat"
 * @param {string} sport     e.g. "NBA"
 */
export function findTeamVenue(teamName, sport) {
  if (!teamName?.trim() || !sport) return null;
  const map = VENUES[sport];
  if (!map) return null;

  const query = teamName.toLowerCase().trim();

  // Exact match
  if (map[query]) return map[query];

  // Key is contained in the query (e.g. "heat" in "miami heat")
  for (const [keyword, venue] of Object.entries(map)) {
    if (query.includes(keyword)) return venue;
  }

  return null;
}
