// ─── Team Season Ticket Portal URLs ───────────────────────────────────────────
// Maps sport + team name keywords → official season ticket purchase page.
// Keyed by sport value (matches CreatePodScreen SPORTS values).
// Keywords are lowercase; matching is case-insensitive substring.
//
// ⚠️  These URLs point to official team pages and may change each season.
//     Verify and update annually, or when a team relocates/rebrands.
// ─────────────────────────────────────────────────────────────────────────────

const URLS = {

  // ── NBA ─────────────────────────────────────────────────────────────────────
  NBA: {
    "hawks":              "https://www.nba.com/hawks/tickets/season-tickets",
    "celtics":            "https://www.nba.com/celtics/tickets/season-tickets",
    "nets":               "https://www.nba.com/nets/tickets/season-tickets",
    "hornets":            "https://www.nba.com/hornets/tickets/season-tickets",
    "bulls":              "https://www.nba.com/bulls/tickets/season-tickets",
    "cavaliers":          "https://www.nba.com/cavaliers/tickets/season-tickets",
    "cavs":               "https://www.nba.com/cavaliers/tickets/season-tickets",
    "mavericks":          "https://www.nba.com/mavericks/tickets/season-tickets",
    "mavs":               "https://www.nba.com/mavericks/tickets/season-tickets",
    "nuggets":            "https://www.nba.com/nuggets/tickets/season-tickets",
    "pistons":            "https://www.nba.com/pistons/tickets/season-tickets",
    "warriors":           "https://www.nba.com/warriors/tickets/season-tickets",
    "rockets":            "https://www.nba.com/rockets/tickets/season-tickets",
    "pacers":             "https://www.nba.com/pacers/tickets/season-tickets",
    "clippers":           "https://www.nba.com/clippers/tickets/season-tickets",
    "lakers":             "https://www.nba.com/lakers/tickets/season-tickets",
    "grizzlies":          "https://www.nba.com/grizzlies/tickets/season-tickets",
    "heat":               "https://www.nba.com/heat/tickets/season-tickets",
    "bucks":              "https://www.nba.com/bucks/tickets/season-tickets",
    "timberwolves":       "https://www.nba.com/timberwolves/tickets/season-tickets",
    "wolves":             "https://www.nba.com/timberwolves/tickets/season-tickets",
    "pelicans":           "https://www.nba.com/pelicans/tickets/season-tickets",
    "knicks":             "https://www.nba.com/knicks/tickets/season-tickets",
    "thunder":            "https://www.nba.com/thunder/tickets/season-tickets",
    "magic":              "https://www.nba.com/magic/tickets/season-tickets",
    "76ers":              "https://www.nba.com/sixers/tickets/season-tickets",
    "sixers":             "https://www.nba.com/sixers/tickets/season-tickets",
    "suns":               "https://www.nba.com/suns/tickets/season-tickets",
    "trail blazers":      "https://www.nba.com/blazers/tickets/season-tickets",
    "blazers":            "https://www.nba.com/blazers/tickets/season-tickets",
    "kings":              "https://www.nba.com/kings/tickets/season-tickets",
    "spurs":              "https://www.nba.com/spurs/tickets/season-tickets",
    "raptors":            "https://www.nba.com/raptors/tickets/season-tickets",
    "jazz":               "https://www.nba.com/jazz/tickets/season-tickets",
    "wizards":            "https://www.nba.com/wizards/tickets/season-tickets",
  },

  // ── NFL ─────────────────────────────────────────────────────────────────────
  NFL: {
    "cardinals":          "https://www.azcardinals.com/tickets/season-tickets",
    "falcons":            "https://www.atlantafalcons.com/tickets/season-tickets",
    "ravens":             "https://www.baltimoreravens.com/tickets/season-tickets",
    "bills":              "https://www.buffalobills.com/tickets/season-tickets",
    "panthers":           "https://www.panthers.com/tickets/season-tickets",
    "bears":              "https://www.chicagobears.com/tickets/season-tickets",
    "bengals":            "https://www.bengals.com/tickets/season-tickets",
    "browns":             "https://www.clevelandbrowns.com/tickets/season-tickets",
    "cowboys":            "https://www.dallascowboys.com/tickets/season-tickets",
    "broncos":            "https://www.denverbroncos.com/tickets/season-tickets",
    "lions":              "https://www.detroitlions.com/tickets/season-tickets",
    "packers":            "https://www.packers.com/tickets/season-tickets",
    "texans":             "https://www.houstontexans.com/tickets/season-tickets",
    "colts":              "https://www.colts.com/tickets/season-tickets",
    "jaguars":            "https://www.jaguars.com/tickets/season-tickets",
    "chiefs":             "https://www.chiefs.com/tickets/season-tickets",
    "raiders":            "https://www.raiders.com/tickets/season-tickets",
    "chargers":           "https://www.chargers.com/tickets/season-tickets",
    "rams":               "https://www.therams.com/tickets/season-tickets",
    "dolphins":           "https://www.miamidolphins.com/tickets/season-tickets",
    "vikings":            "https://www.vikings.com/tickets/season-tickets",
    "patriots":           "https://www.patriots.com/tickets/season-tickets",
    "saints":             "https://www.neworleanssaints.com/tickets/season-tickets",
    "giants":             "https://www.giants.com/tickets/season-tickets",
    "jets":               "https://www.newyorkjets.com/tickets/season-tickets",
    "eagles":             "https://www.philadelphiaeagles.com/tickets/season-tickets",
    "steelers":           "https://www.steelers.com/tickets/season-tickets",
    "49ers":              "https://www.49ers.com/tickets/season-tickets",
    "seahawks":           "https://www.seahawks.com/tickets/season-tickets",
    "buccaneers":         "https://www.buccaneers.com/tickets/season-tickets",
    "bucs":               "https://www.buccaneers.com/tickets/season-tickets",
    "titans":             "https://www.titansonline.com/tickets/season-tickets",
    "commanders":         "https://www.commanders.com/tickets/season-tickets",
  },

  // ── MLB ─────────────────────────────────────────────────────────────────────
  MLB: {
    "diamondbacks":       "https://www.mlb.com/dbacks/tickets/season-tickets",
    "d-backs":            "https://www.mlb.com/dbacks/tickets/season-tickets",
    "braves":             "https://www.mlb.com/braves/tickets/season-tickets",
    "orioles":            "https://www.mlb.com/orioles/tickets/season-tickets",
    "red sox":            "https://www.mlb.com/redsox/tickets/season-tickets",
    "cubs":               "https://www.mlb.com/cubs/tickets/season-tickets",
    "white sox":          "https://www.mlb.com/whitesox/tickets/season-tickets",
    "reds":               "https://www.mlb.com/reds/tickets/season-tickets",
    "guardians":          "https://www.mlb.com/guardians/tickets/season-tickets",
    "rockies":            "https://www.mlb.com/rockies/tickets/season-tickets",
    "tigers":             "https://www.mlb.com/tigers/tickets/season-tickets",
    "astros":             "https://www.mlb.com/astros/tickets/season-tickets",
    "royals":             "https://www.mlb.com/royals/tickets/season-tickets",
    "angels":             "https://www.mlb.com/angels/tickets/season-tickets",
    "dodgers":            "https://www.mlb.com/dodgers/tickets/season-tickets",
    "marlins":            "https://www.mlb.com/marlins/tickets/season-tickets",
    "brewers":            "https://www.mlb.com/brewers/tickets/season-tickets",
    "twins":              "https://www.mlb.com/twins/tickets/season-tickets",
    "mets":               "https://www.mlb.com/mets/tickets/season-tickets",
    "yankees":            "https://www.mlb.com/yankees/tickets/season-tickets",
    "athletics":          "https://www.mlb.com/athletics/tickets/season-tickets",
    "phillies":           "https://www.mlb.com/phillies/tickets/season-tickets",
    "pirates":            "https://www.mlb.com/pirates/tickets/season-tickets",
    "padres":             "https://www.mlb.com/padres/tickets/season-tickets",
    "giants":             "https://www.mlb.com/giants/tickets/season-tickets",
    "mariners":           "https://www.mlb.com/mariners/tickets/season-tickets",
    "cardinals":          "https://www.mlb.com/cardinals/tickets/season-tickets",
    "rays":               "https://www.mlb.com/rays/tickets/season-tickets",
    "rangers":            "https://www.mlb.com/rangers/tickets/season-tickets",
    "blue jays":          "https://www.mlb.com/bluejays/tickets/season-tickets",
    "nationals":          "https://www.mlb.com/nationals/tickets/season-tickets",
  },

  // ── NHL ─────────────────────────────────────────────────────────────────────
  NHL: {
    "ducks":              "https://www.nhl.com/ducks/tickets/season-tickets",
    "bruins":             "https://www.nhl.com/bruins/tickets/season-tickets",
    "sabres":             "https://www.nhl.com/sabres/tickets/season-tickets",
    "flames":             "https://www.nhl.com/flames/tickets/season-tickets",
    "hurricanes":         "https://www.nhl.com/hurricanes/tickets/season-tickets",
    "canes":              "https://www.nhl.com/hurricanes/tickets/season-tickets",
    "blackhawks":         "https://www.nhl.com/blackhawks/tickets/season-tickets",
    "avalanche":          "https://www.nhl.com/avalanche/tickets/season-tickets",
    "avs":                "https://www.nhl.com/avalanche/tickets/season-tickets",
    "blue jackets":       "https://www.nhl.com/bluejackets/tickets/season-tickets",
    "stars":              "https://www.nhl.com/stars/tickets/season-tickets",
    "red wings":          "https://www.nhl.com/redwings/tickets/season-tickets",
    "oilers":             "https://www.nhl.com/oilers/tickets/season-tickets",
    "panthers":           "https://www.nhl.com/panthers/tickets/season-tickets",
    "kings":              "https://www.nhl.com/kings/tickets/season-tickets",
    "wild":               "https://www.nhl.com/wild/tickets/season-tickets",
    "canadiens":          "https://www.nhl.com/canadiens/tickets/season-tickets",
    "habs":               "https://www.nhl.com/canadiens/tickets/season-tickets",
    "predators":          "https://www.nhl.com/predators/tickets/season-tickets",
    "preds":              "https://www.nhl.com/predators/tickets/season-tickets",
    "devils":             "https://www.nhl.com/devils/tickets/season-tickets",
    "islanders":          "https://www.nhl.com/islanders/tickets/season-tickets",
    "rangers":            "https://www.nhl.com/rangers/tickets/season-tickets",
    "senators":           "https://www.nhl.com/senators/tickets/season-tickets",
    "sens":               "https://www.nhl.com/senators/tickets/season-tickets",
    "flyers":             "https://www.nhl.com/flyers/tickets/season-tickets",
    "penguins":           "https://www.nhl.com/penguins/tickets/season-tickets",
    "pens":               "https://www.nhl.com/penguins/tickets/season-tickets",
    "sharks":             "https://www.nhl.com/sharks/tickets/season-tickets",
    "kraken":             "https://www.nhl.com/kraken/tickets/season-tickets",
    "blues":              "https://www.nhl.com/blues/tickets/season-tickets",
    "lightning":          "https://www.nhl.com/lightning/tickets/season-tickets",
    "bolts":              "https://www.nhl.com/lightning/tickets/season-tickets",
    "maple leafs":        "https://www.nhl.com/mapleleafs/tickets/season-tickets",
    "leafs":              "https://www.nhl.com/mapleleafs/tickets/season-tickets",
    "utah hockey":        "https://www.nhl.com/utah/tickets/season-tickets",
    "canucks":            "https://www.nhl.com/canucks/tickets/season-tickets",
    "golden knights":     "https://www.nhl.com/goldenknights/tickets/season-tickets",
    "capitals":           "https://www.nhl.com/capitals/tickets/season-tickets",
    "caps":               "https://www.nhl.com/capitals/tickets/season-tickets",
    "jets":               "https://www.nhl.com/jets/tickets/season-tickets",
  },

  // ── MLS ─────────────────────────────────────────────────────────────────────
  MLS: {
    "galaxy":             "https://www.lagalaxy.com/tickets/season-tickets",
    "lafc":               "https://www.lafc.com/tickets/season-tickets",
    "atlanta united":     "https://www.atlutd.com/tickets/season-tickets",
    "sounders":           "https://www.soundersfc.com/tickets/season-tickets",
    "portland timbers":   "https://www.timbers.com/tickets/season-tickets",
    "timbers":            "https://www.timbers.com/tickets/season-tickets",
    "red bulls":          "https://www.newyorkredbulls.com/tickets/season-tickets",
    "nycfc":              "https://www.nycfc.com/tickets/season-tickets",
    "new york city":      "https://www.nycfc.com/tickets/season-tickets",
    "columbus crew":      "https://www.columbuscrew.com/tickets/season-tickets",
    "crew":               "https://www.columbuscrew.com/tickets/season-tickets",
    "sporting kc":        "https://www.sportingkc.com/tickets/season-tickets",
    "sporting kansas":    "https://www.sportingkc.com/tickets/season-tickets",
    "fc dallas":          "https://www.fcdallas.com/tickets/season-tickets",
    "chicago fire":       "https://www.chicago-fire.com/tickets/season-tickets",
    "fire":               "https://www.chicago-fire.com/tickets/season-tickets",
    "toronto fc":         "https://www.torontofc.ca/tickets/season-tickets",
    "minnesota united":   "https://www.mnufc.com/tickets/season-tickets",
    "loons":              "https://www.mnufc.com/tickets/season-tickets",
    "inter miami":        "https://www.intermiamicf.com/tickets/season-tickets",
    "miami cf":           "https://www.intermiamicf.com/tickets/season-tickets",
    "nashville sc":       "https://www.nashvillesc.com/tickets/season-tickets",
    "austin fc":          "https://www.austinfc.com/tickets/season-tickets",
    "st. louis city":     "https://www.stlcitysc.com/tickets/season-tickets",
    "real salt lake":     "https://www.rsl.com/tickets/season-tickets",
    "rsl":                "https://www.rsl.com/tickets/season-tickets",
  },

  // ── WNBA ────────────────────────────────────────────────────────────────────
  WNBA: {
    "sky":                "https://www.wnba.com/sky/tickets/season-tickets",
    "chicago sky":        "https://www.wnba.com/sky/tickets/season-tickets",
    "dream":              "https://www.wnba.com/dream/tickets/season-tickets",
    "fever":              "https://www.wnba.com/fever/tickets/season-tickets",
    "sparks":             "https://www.wnba.com/sparks/tickets/season-tickets",
    "lynx":               "https://www.wnba.com/lynx/tickets/season-tickets",
    "liberty":            "https://www.wnba.com/liberty/tickets/season-tickets",
    "sun":                "https://www.wnba.com/sun/tickets/season-tickets",
    "mystics":            "https://www.wnba.com/mystics/tickets/season-tickets",
    "wings":              "https://www.wnba.com/wings/tickets/season-tickets",
    "mercury":            "https://www.wnba.com/mercury/tickets/season-tickets",
    "storm":              "https://www.wnba.com/storm/tickets/season-tickets",
    "aces":               "https://www.wnba.com/aces/tickets/season-tickets",
    "las vegas aces":     "https://www.wnba.com/aces/tickets/season-tickets",
  },

  // ── NCAA Football ────────────────────────────────────────────────────────────
  "ncaa-football": {
    "alabama":            "https://rolltide.com/sports/football/tickets",
    "crimson tide":       "https://rolltide.com/sports/football/tickets",
    "ohio state":         "https://ohiostatebuckeyes.com/sports/football/tickets",
    "buckeyes":           "https://ohiostatebuckeyes.com/sports/football/tickets",
    "michigan":           "https://mgoblue.com/sports/football/tickets",
    "wolverines":         "https://mgoblue.com/sports/football/tickets",
    "georgia":            "https://georgiadogs.com/sports/football/tickets",
    "bulldogs":           "https://georgiadogs.com/sports/football/tickets",
    "clemson":            "https://clemsontigers.com/sports/football/tickets",
    "tigers":             "https://clemsontigers.com/sports/football/tickets",
    "notre dame":         "https://fightingirish.com/sports/football/tickets",
    "fighting irish":     "https://fightingirish.com/sports/football/tickets",
    "texas":              "https://texassports.com/sports/football/tickets",
    "longhorns":          "https://texassports.com/sports/football/tickets",
    "oklahoma":           "https://soonersports.com/sports/football/tickets",
    "sooners":            "https://soonersports.com/sports/football/tickets",
    "lsu":                "https://lsusports.net/sports/football/tickets",
    "tigers lsu":         "https://lsusports.net/sports/football/tickets",
    "usc":                "https://usctrojans.com/sports/football/tickets",
    "trojans":            "https://usctrojans.com/sports/football/tickets",
    "oregon":             "https://goducks.com/sports/football/tickets",
    "ducks":              "https://goducks.com/sports/football/tickets",
    "penn state":         "https://gopsusports.com/sports/football/tickets",
    "nittany lions":      "https://gopsusports.com/sports/football/tickets",
    "florida":            "https://floridagators.com/sports/football/tickets",
    "gators":             "https://floridagators.com/sports/football/tickets",
    "tennessee":          "https://utsports.com/sports/football/tickets",
    "volunteers":         "https://utsports.com/sports/football/tickets",
    "iowa":               "https://hawkeyesports.com/sports/football/tickets",
    "hawkeyes":           "https://hawkeyesports.com/sports/football/tickets",
    "miami hurricanes":   "https://hurricanesports.com/sports/football/tickets",
    "auburn":             "https://auburntigers.com/sports/football/tickets",
    "wisconsin":          "https://uwbadgers.com/sports/football/tickets",
    "badgers":            "https://uwbadgers.com/sports/football/tickets",
    "utah":               "https://utahutes.com/sports/football/tickets",
    "utes":               "https://utahutes.com/sports/football/tickets",
    "michigan state":     "https://msuspartans.com/sports/football/tickets",
    "spartans":           "https://msuspartans.com/sports/football/tickets",
    "washington":         "https://gohuskies.com/sports/football/tickets",
    "huskies":            "https://gohuskies.com/sports/football/tickets",
    "florida state":      "https://seminoles.com/sports/football/tickets",
    "seminoles":          "https://seminoles.com/sports/football/tickets",
  },

  // ── NCAA Men's Basketball ─────────────────────────────────────────────────
  "ncaa-basketball": {
    "duke":               "https://goduke.com/sports/mens-basketball/tickets",
    "blue devils":        "https://goduke.com/sports/mens-basketball/tickets",
    "kentucky":           "https://ukathletics.com/sports/mens-basketball/tickets",
    "wildcats":           "https://ukathletics.com/sports/mens-basketball/tickets",
    "kansas":             "https://kuathletics.com/sports/mens-basketball/tickets",
    "jayhawks":           "https://kuathletics.com/sports/mens-basketball/tickets",
    "north carolina":     "https://goheels.com/sports/mens-basketball/tickets",
    "tar heels":          "https://goheels.com/sports/mens-basketball/tickets",
    "unc":                "https://goheels.com/sports/mens-basketball/tickets",
    "uconn":              "https://uconnhuskies.com/sports/mens-basketball/tickets",
    "huskies uconn":      "https://uconnhuskies.com/sports/mens-basketball/tickets",
    "villanova":          "https://villanova.com/sports/mens-basketball/tickets",
    "wildcats nova":      "https://villanova.com/sports/mens-basketball/tickets",
    "gonzaga":            "https://gozags.com/sports/mens-basketball/tickets",
    "zags":               "https://gozags.com/sports/mens-basketball/tickets",
    "michigan state":     "https://msuspartans.com/sports/mens-basketball/tickets",
    "ucla":               "https://uclabruins.com/sports/mens-basketball/tickets",
    "bruins":             "https://uclabruins.com/sports/mens-basketball/tickets",
    "arizona":            "https://arizonawildcats.com/sports/mens-basketball/tickets",
    "purdue":             "https://purduesports.com/sports/mens-basketball/tickets",
    "boilermakers":       "https://purduesports.com/sports/mens-basketball/tickets",
    "indiana":            "https://iuhoosiers.com/sports/mens-basketball/tickets",
    "hoosiers":           "https://iuhoosiers.com/sports/mens-basketball/tickets",
    "houston":            "https://uhcougars.com/sports/mens-basketball/tickets",
    "cougars":            "https://uhcougars.com/sports/mens-basketball/tickets",
    "marquette":          "https://gomarquette.com/sports/mens-basketball/tickets",
    "golden eagles":      "https://gomarquette.com/sports/mens-basketball/tickets",
    "creighton":          "https://gocreighton.com/sports/mens-basketball/tickets",
    "bluejays":           "https://gocreighton.com/sports/mens-basketball/tickets",
    "louisville":         "https://gocards.com/sports/mens-basketball/tickets",
    "cardinals louisville":"https://gocards.com/sports/mens-basketball/tickets",
  },

  // ── NCAA Women's Basketball ───────────────────────────────────────────────
  "ncaa-wbasketball": {
    "uconn":              "https://uconnhuskies.com/sports/womens-basketball/tickets",
    "south carolina":     "https://gamecocksonline.com/sports/womens-basketball/tickets",
    "gamecocks":          "https://gamecocksonline.com/sports/womens-basketball/tickets",
    "iowa":               "https://hawkeyesports.com/sports/womens-basketball/tickets",
    "hawkeyes":           "https://hawkeyesports.com/sports/womens-basketball/tickets",
    "lsu":                "https://lsusports.net/sports/womens-basketball/tickets",
    "stanford":           "https://gostanford.com/sports/womens-basketball/tickets",
    "cardinal":           "https://gostanford.com/sports/womens-basketball/tickets",
    "tennessee":          "https://utsports.com/sports/womens-basketball/tickets",
    "notre dame":         "https://fightingirish.com/sports/womens-basketball/tickets",
    "baylor":             "https://baylorbears.com/sports/womens-basketball/tickets",
    "bears":              "https://baylorbears.com/sports/womens-basketball/tickets",
    "nc state":           "https://gopack.com/sports/womens-basketball/tickets",
    "wolfpack":           "https://gopack.com/sports/womens-basketball/tickets",
    "oklahoma":           "https://soonersports.com/sports/womens-basketball/tickets",
    "virginia tech":      "https://hokiesports.com/sports/womens-basketball/tickets",
    "hokies":             "https://hokiesports.com/sports/womens-basketball/tickets",
  },

  // ── NCAA Baseball ─────────────────────────────────────────────────────────
  "ncaa-baseball": {
    "lsu":                "https://lsusports.net/sports/baseball/tickets",
    "vanderbilt":         "https://vucommodores.com/sports/baseball/tickets",
    "commodores":         "https://vucommodores.com/sports/baseball/tickets",
    "florida":            "https://floridagators.com/sports/baseball/tickets",
    "gators":             "https://floridagators.com/sports/baseball/tickets",
    "texas":              "https://texassports.com/sports/baseball/tickets",
    "arkansas":           "https://arkansasrazorbacks.com/sports/baseball/tickets",
    "razorbacks":         "https://arkansasrazorbacks.com/sports/baseball/tickets",
    "arizona":            "https://arizonawildcats.com/sports/baseball/tickets",
    "stanford":           "https://gostanford.com/sports/baseball/tickets",
    "miami":              "https://hurricanesports.com/sports/baseball/tickets",
    "oregon state":       "https://osubeavers.com/sports/baseball/tickets",
    "beavers":            "https://osubeavers.com/sports/baseball/tickets",
    "ole miss":           "https://olemisssports.com/sports/baseball/tickets",
    "rebels":             "https://olemisssports.com/sports/baseball/tickets",
    "texas a&m":          "https://12thman.com/sports/baseball/tickets",
    "aggies":             "https://12thman.com/sports/baseball/tickets",
    "north carolina":     "https://goheels.com/sports/baseball/tickets",
    "tcu":                "https://gofrogs.com/sports/baseball/tickets",
    "horned frogs":       "https://gofrogs.com/sports/baseball/tickets",
  },

  // ── NCAA Hockey ──────────────────────────────────────────────────────────
  "ncaa-hockey": {
    "minnesota":          "https://gophersports.com/sports/mens-hockey/tickets",
    "gophers":            "https://gophersports.com/sports/mens-hockey/tickets",
    "north dakota":       "https://fightinghawks.com/sports/mens-hockey/tickets",
    "fighting hawks":     "https://fightinghawks.com/sports/mens-hockey/tickets",
    "boston university":  "https://goterriers.com/sports/mens-hockey/tickets",
    "terriers":           "https://goterriers.com/sports/mens-hockey/tickets",
    "michigan":           "https://mgoblue.com/sports/mens-hockey/tickets",
    "wisconsin":          "https://uwbadgers.com/sports/mens-hockey/tickets",
    "denver":             "https://denverpioneers.com/sports/mens-hockey/tickets",
    "pioneers":           "https://denverpioneers.com/sports/mens-hockey/tickets",
    "boston college":     "https://bceagles.com/sports/mens-hockey/tickets",
    "cornell":            "https://cornellbigred.com/sports/mens-hockey/tickets",
    "big red":            "https://cornellbigred.com/sports/mens-hockey/tickets",
    "quinnipiac":         "https://quinnipiacbobcats.com/sports/mens-hockey/tickets",
    "bobcats":            "https://quinnipiacbobcats.com/sports/mens-hockey/tickets",
    "maine":              "https://goblackbears.com/sports/mens-hockey/tickets",
    "black bears":        "https://goblackbears.com/sports/mens-hockey/tickets",
  },
};

// ─── Lookup function ──────────────────────────────────────────────────────────
/**
 * Returns the official season ticket URL for a team, or null if not found.
 * @param {string} teamName  - what the captain typed, e.g. "Chicago Bulls"
 * @param {string} sport     - sport value, e.g. "NBA", "ncaa-football"
 */
export function findTeamTicketUrl(teamName, sport) {
  if (!teamName?.trim() || !sport) return null;
  const map = URLS[sport];
  if (!map) return null;

  const query = teamName.toLowerCase().trim();

  // 1. Exact match
  if (map[query]) return map[query];

  // 2. Map key is contained in the query (e.g. "bulls" in "chicago bulls")
  for (const [keyword, url] of Object.entries(map)) {
    if (query.includes(keyword)) return url;
  }

  // 3. Query is contained in a map key (handles partial typing)
  for (const [keyword, url] of Object.entries(map)) {
    if (keyword.includes(query) && query.length >= 4) return url;
  }

  return null;
}
